GET http://localhost:4000/uam
# irembo.com/getone

###
GET http://localhost:4000/uam/users

###
POST http://localhost:4000/enroll/signup

###
POST http://localhost:4000/uam/signin
Accept: application/json
Content-Type: application/json

{
    "profilePhoto": "https://picsum.photos/200/300",
    "name": "Christopher Kwizera",
    "email": "christophekwizera@gmail.com",
    "password": "kamunikwi",
    "gender": "Male",
    "age": "20",
    "national_id": "1199980015433063",
    "phoneNumber": "0784824295",
    "document": "https://picsum.photos/200/300",
    "dateOfBirth": "1999-03-08",
    "maritalStatus": "SINGLE",
    "nationality": "Rwandan"
}

###
POST http://localhost:2000/signin
Accept: application/json
Content-Type: application/json

{
    "email": "christophekwizera@gmail.com",
    "password": "zxcvbnm"
}

###
POST http://localhost:2000/reset-password
Accept: application/json
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzdG9waGVrd2l6ZXJhQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDc4NDgyNDI5NSIsImlhdCI6MTY2MDQ5OTI0MH0.u41lfhFl4VNU2Uz-SuMFjK-GWNbdeH8dkS1mhbsrwPI

{
    "password": "zxcvbnm"
}

###
POST http://localhost:2000/forgot-password
Accept: application/json
Content-Type: application/json

{
    "email": "christophekwizera@gmail.com"
}


###
POST http://localhost:2000/get-signed-urls
Accept: application/json
Content-Type: application/json

{
    "key": "27163fa5-d96e-4430-9e9c-e62b35da8c43.jpeg"
}

###
POST http://localhost:4000/uam/create-signed-urls
Accept: application/json
Content-Type: application/json

{
    "type": "image/jpeg"
}

###
GET http://localhost:2000/validate-user/630512a2934bf6bd73cd76e3
Accept: application/json
Content-Type: application/json
